application: ilmoitus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: ilmoitus.application

libraries:
- name: webapp2
  version: "2.5.1"

- name: PIL
  version: "1.1.7"

bullitins:
- appstats: on