application: ilmoitus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: ilmoitus.application

- url: /stats.*
  script: google.appengine.ext.appstats.ui.app

libraries:
- name: webapp2
  version: "latest"

- name: PIL
  version: "1.1.7"

builtins:
- appstats: on