application: sns-ilmoitus
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stats.*
  script: google.appengine.ext.appstats.ui.app
  login: admin

- ur: /static
  static_dir: static
  login: required

- url: .*
  script: ilmoitus.application
  login: required

libraries:
- name: webapp2
  version: "latest"

- name: PIL
  version: "1.1.7"

builtins:
- appstats: on